### PR TITLE
Handle unanswered questions and updated dialogue

### PR DESCRIPTION
**Pull request by ec-m**
- handling of unanswered questions
- small bug fixes
- adjusted some english in the phrases

@josephbirkner can you change the base to our active sprint branch as soon as there is one? Thanks :)

### CODE REVIEW

**Comment by ec-m** [comment]
* solved merge conflicts using try-imports for the ROS stuff
* added reminder of for customer to pick up their ice cream
* adjusted the payment interface to send the information about what was ordered to the payment system
* Adjusted driving dialogue to correctly answer (first) messages like "hey roboy. i want ice cream. meet me at the mensa".

**Review by theycallmefm — APPROVED** [review]

**Comment by ec-m** [comment]
Added the webserver and changed the communication via the webserver with AD to the new interface.

**Comment by josephbirkner** [comment]
@ec-m Any update wrt/ the failing tests?

**Comment by ec-m** [comment]
> @ec-m Any update wrt/ the failing tests?

It's unclear why they are failing. Locally everything runs fine 🙈

**Comment by ec-m** [comment]
This PR is covered by #17

**Pull request closed without merging**
